# Generated by Django 3.2.22 on 2023-10-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yousta', '0002_carts_category_cloths_clothvarients_offers_orders_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloths',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yousta.category'),
        ),
    ]
