# Generated by Django 3.2.22 on 2023-11-09 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yousta', '0003_cloths_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='clothvarient',
        ),
        migrations.AddField(
            model_name='reviews',
            name='cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yousta.cloths'),
        ),
    ]
